### ISSUE TITLE
'ValueError'  while loading  mtcnn detector npy files 

### ISSUE THREAD

**Issue by Jumabek** [foamliu/InsightFace-v2#11]
Do you have any idea why this is happening. 
I checked, file exists.

System Specs:
Ubuntu 18.04
python 3.6.7
numpy 1.16.4

Full code:

```
jumabek@dlone:~/workspace/InsightFace-v2$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.load('mtcnn/weights/pnet.npy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jumabek/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/jumabek/.local/lib/python3.6/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

```

**Comment by Jumabek** [comment]
`np.load('mtcnn/weights/pnet.npy',**allow_pickle=True**)`
solved the issue
